name: download files

on: 
  push:
    path: 
      - 'download-link.md'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: test secret 
        run: |
          echo "--token=${{secrets.WEB3_API}} $(ls *.md)"
      - name: test node 
        run: |
          cd web3-quick 
          npm install 
          cd ..


      - name: install YT-DL 
        run: | 
          wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
          chmod a+rx /usr/local/bin/youtube-dl
      - name: checkout current dir 
        run: ls 
      
      - name: download video 
        run: |
          ls
          youtube-dl -i -R 10 -r 50k $(echo $(cat download-link.md))
          ls
      - name: save all video 
        run: |
          ls *.mp4 >> mp4
          node web3-quick/put-files.js --token=${{secrets.WEB3_API}} $(ls *.mp4)
          

  
