name: download files

on: 
  push:
    path: 
      - 'download-link.md'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - name: install YT-DL 
        run: | 
          wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
          chmod a+rx /usr/local/bin/youtube-dl
      - name: checkout current dir 
        run: ls 
      
      - name: download video 
        run: |
          ls
          youtube-dl $(echo $(cat download-link.md))
          ls
  
