name: download file from cloud

on: 
  push:
    paths: 
      - 'download-cloud.md'

jobs:
  init: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FedericoCarboni/setup-ffmpeg@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: test node 
        run: |
          cd web3-quick 
          npm install 
          cd ..
      - name: dl cloud data
        run: |
          cat download-cloud.md | while read line; do
            wget -O  "$line"
            echo "$line"
          done
      - name: upload files
        env:
          API: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweENGQjAwNDFlREI2MkQwODNFYTVEMUE1ZUMxMmE5MDQ5NzVCN2FFQmQiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NjAwNjg4NDAyMjIsIm5hbWUiOiJtaXRsZXJuZW4ifQ.VCIyU4dYUUDWbJO59-XHdkA8gEL4ZseiGbF1D0eYPm8
        run: |
          # ls *.mp4 >> mp4
          node web3-quick/put-files.js --token="${API}" $(ls *.mp4 *.mkv *.webm)